"""initial_schema

Revision ID: a4ab2ba19a39
Revises:
Create Date: 2026-07-11 17:06:11.838240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a4ab2ba19a39"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amiibo_stock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Website", sa.String(), nullable=False),
        sa.Column("Title", sa.String(), nullable=False),
        sa.Column("Price", sa.String(), nullable=False),
        sa.Column("Stock", sa.String(), nullable=False),
        sa.Column("Colour", sa.String(), nullable=False),
        sa.Column("URL", sa.String(), nullable=False),
        sa.Column("Image", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("missed_count", sa.Integer(), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(), nullable=True),
        sa.Column("last_notified_status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("Website", "URL"),
    )
    op.create_table(
        "last_scraped",
        sa.Column("stockist", sa.String(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("last_healthy_count", sa.Integer(), nullable=False),
        sa.Column("consecutive_unhealthy_obs", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("stockist"),
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("website", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("stock_status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scraping_failures",
        sa.Column("stockist", sa.String(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_failure", sa.DateTime(), nullable=False),
        sa.Column("last_success", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("stockist"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scraping_failures")
    op.drop_table("notification_outbox")
    op.drop_table("last_scraped")
    op.drop_table("amiibo_stock")
    # ### end Alembic commands ###
